import { Montserrat } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "MarketLogic - Eventos Colombia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
